# Copyright (C) 2015-2016 Ahmed Charles - acharles@outlook.com
# Distributed under the MIT License.
#    (See accompanying file LICENSE.txt or copy at
#          http://opensource.org/licenses/MIT)

sudo: false
language: rust
cache: cargo
addons:
  apt:
    packages:
      - realpath
script:
  - cargo build --verbose
  - cargo test --verbose
  - ./run-tests
