#!/bin/sh

# Copyright (C) 2016 Ahmed Charles - acharles@outlook.com
# Distributed under the MIT License.
#    (See accompanying file LICENSE.txt or copy at
#          http://opensource.org/licenses/MIT)

LUA=`realpath puc-lua/src/tests/lua`
make -C puc-lua/src/tests/libs
mkdir -p puc-lua/src/tests/libs/P1
(cd puc-lua/src/tests; $LUA all.lua)
rm puc-lua/src/tests/libs/lib1.so \
   puc-lua/src/tests/libs/lib11.so \
   puc-lua/src/tests/libs/lib2-v2.so \
   puc-lua/src/tests/libs/lib21.so \
   puc-lua/src/tests/time-debug.txt
