#!/bin/sh

# Copyright (C) 2016 Ahmed Charles - acharles@outlook.com
# Distributed under the MIT License.
#    (See accompanying file LICENSE.txt or copy at
#          http://opensource.org/licenses/MIT)

LUA=`realpath target/debug/lua`
mkdir -p puc-lua/src/tests/libs/P1
(cd puc-lua/src/tests; $LUA all.lua)
rm puc-lua/src/tests/time-debug.txt
