/* this file was generated by glue.c; do not modify it by hand */
#![allow(unused_imports, dead_code, non_camel_case_types)]
use libc::*;
/* luaconf.h */
pub const LUA_PATH_DEFAULT: &'static str = "/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua";
pub const LUA_CPATH_DEFAULT: &'static str = "/usr/local/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;./?.so";
pub const LUA_EXTRASPACE: c_int = 8;
pub const LUA_IDSIZE: c_int = 60;
pub type LUA_KCONTEXT = ptrdiff_t;
pub const LUAL_BUFFERSIZE: c_int = 8192;
pub type LUA_NUMBER = c_double;
pub type LUA_UNSIGNED = uint64_t;
pub type LUA_INTEGER = int64_t;
pub const LUA_MAXINTEGER: LUA_INTEGER = 9223372036854775807;
pub const LUA_MININTEGER: LUA_INTEGER = -9223372036854775808;
/* lua.h */
pub const LUA_VERSION_MAJOR: &'static str = "5";
pub const LUA_VERSION_MINOR: &'static str = "3";
pub const LUA_VERSION_NUM: c_int = 503;
pub const LUA_VERSION_RELEASE: &'static str = "3";
pub const LUA_VERSION: &'static str = "Lua 5.3";
pub const LUA_RELEASE: &'static str = "Lua 5.3.3";
pub const LUA_COPYRIGHT: &'static str = "Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio";
pub const LUA_AUTHORS: &'static str = "R. Ierusalimschy, L. H. de Figueiredo, W. Celes";
#[cfg(debug_assertions)]
pub const LUA_REGISTRYINDEX: c_int = -51000;
#[cfg(not(debug_assertions))]
pub const LUA_REGISTRYINDEX: c_int = -1001000;
/* lauxlib.h */
pub const LUAL_NUMSIZES: c_int = 136;
pub const LUA_FILEHANDLE: &'static str = "FILE*";
/* lualib.h */
pub const LUA_COLIBNAME: &'static str = "coroutine";
pub const LUA_TABLIBNAME: &'static str = "table";
pub const LUA_IOLIBNAME: &'static str = "io";
pub const LUA_OSLIBNAME: &'static str = "os";
pub const LUA_STRLIBNAME: &'static str = "string";
pub const LUA_UTF8LIBNAME: &'static str = "utf8";
pub const LUA_BITLIBNAME: &'static str = "bit32";
pub const LUA_MATHLIBNAME: &'static str = "math";
pub const LUA_DBLIBNAME: &'static str = "debug";
pub const LUA_LOADLIBNAME: &'static str = "package";
